import type { Word } from './word';

export const words: Word[] = [
    { text: 'Apple', category: 'Fruit' },
    { text: 'Banana', category: 'Fruit' },
    { text: 'Carrot', category: 'Vegetable' },
    { text: 'Dragonfruit', category: 'Fruit' },
    { text: 'Eggplant', category: 'Vegetable' },
    { text: 'Fig', category: 'Fruit' },
    { text: 'Grape', category: 'Fruit' },
    { text: 'Honeydew', category: 'Fruit' },
    { text: 'Iceberg Lettuce', category: 'Vegetable' },
    { text: 'Jackfruit', category: 'Fruit' },
    { text: 'Kale', category: 'Vegetable' },
    { text: 'Lemon', category: 'Fruit' },
    { text: 'Mango', category: 'Fruit' },
    { text: 'Nectarine', category: 'Fruit' },
    { text: 'Olive', category: 'Fruit' },
    { text: 'Pepper', category: 'Vegetable' },
    { text: 'Quince', category: 'Fruit' },
    { text: 'Radish', category: 'Vegetable' },
    { text: 'Spinach', category: 'Vegetable' },
    { text: 'Tomato', category: 'Fruit' },
    { text: 'Ugli Fruit', category: 'Fruit' },
    { text: 'Zucchini', category: 'Vegetable' },
    // Animals
    { text: 'Cat', category: 'Animal' },
    { text: 'Dog', category: 'Animal' },
    { text: 'Elephant', category: 'Animal' },
    { text: 'Tiger', category: 'Animal' },
    { text: 'Bird', category: 'Animal' },
    { text: 'Fish', category: 'Animal' },
    { text: 'Horse', category: 'Animal' },
    { text: 'Cow', category: 'Animal' },
    // Movies
    { text: 'Avatar', category: 'Movie' },
    { text: 'Titanic', category: 'Movie' },
    { text: 'Batman', category: 'Movie' },
    { text: 'Superman', category: 'Movie' },
    { text: 'Star Wars', category: 'Movie' },
    // sports
    { text: 'Football', category: 'Sport' },
    { text: 'Basketball', category: 'Sport' },
    { text: 'Tennis', category: 'Sport' },
    { text: 'Soccer', category: 'Sport' },
    { text: 'Baseball', category: 'Sport' },
    { text: 'Hockey', category: 'Sport' },
    { text: 'Golf', category: 'Sport' },
    { text: 'Cricket', category: 'Sport' },
    { text: 'Rugby', category: 'Sport' },
    { text: 'Swimming', category: 'Sport' },
    // Professions
    { text: 'Doctor', category: 'Profession' },
    { text: 'Teacher', category: 'Profession' },
    { text: 'Engineer', category: 'Profession' },
    { text: 'Artist', category: 'Profession' },
    { text: 'Chef', category: 'Profession' },
    { text: 'Pilot', category: 'Profession' },
    { text: 'Nurse', category: 'Profession' },
    
];
